import React, {
  ReactNode,
  useEffect,
  useId,
  useRef,
  useState
} from 'react';
import Scene from '../scene/Scene';
import { subscribe } from '../scene/download-event';
import {
  AnimationStyle,
  DEBUG_STYLE,
  ExportType,
  MOUNT_DEBUG_NODE_CLASS,
  MOUNT_NODE_CLASS,
  MOUNT_NODE_STYLE
} from '../scene/constants';
import { CameraReducerAction, CameraState } from '../CameraContextProvider/camera-reducer';
import useResizeObserver from 'use-resize-observer';
import { Enlargeable } from '../../data-display/Enlargeable';
import clsx from 'clsx';
import { ModalCloseButton } from '../../data-display/Modal/ModalCloseButton/ModalCloseButton';
import { downloadJSON } from '../../../utils/download';
import { RangeSlider } from '../../data-entry/RangeSlider';
import { ScenePosition } from '../scene/inset-helper';
import {
  DEFAULT_CRYSTAL_TOOLKIT_SCENE_TEXTS,
  type CrystalToolkitSceneTexts
} from '../sceneControlTexts';
import { mergeTexts } from '../../../utils/text';
import {
  createSceneLifecycle,
  useDismissiblePanel,
  useSceneCameraSync,
  useScenePanels,
  useSceneSharedEffects
} from '../sceneComponentShared';
import { requestSceneExport } from '../sceneExport';
import { getSceneSize, hasRenderableSceneData, hideTooltip } from '../sceneComponentUtils';
import { SceneToolbar } from '../SceneToolbar';

export interface CrystalToolkitAnimationSceneProps {
  /**
   * The ID used to identify this component in Dash callbacks
   */
  id?: string;

  /**
   * Dash-assigned callback that should be called whenever any of the
   * properties change
   */
  setProps?: (value: any) => any;

  /**
   * First child will be rendered as the settings panel.
   * Second child will be rendered as the bottom panel (legend).
   */
  children?: ReactNode;

  /**
   * Class name that will wrap around the whole scene component.
   * When enlarged, this class name is applied to the modal-content element.
   */
  className?: string;

  /**
   * Add a debugging view
   */
  debug?: boolean;

  /**
   * Scene JSON, the easiest way to generate this is to use the Scene class
   * in crystal_toolkit.core.scene and its to_json method.
   */
  data: any;

  /**
   * Options used for generating scene.
   * Supported options and their defaults are given as follows:
   * {
   *    antialias: true, // set to false to improve performance
   *    renderer: 'webgl', // 'svg' also an option, used for unit testing
   *    transparentBackground: false, // transparent background
   *    background: '#ffffff', // background color if not transparent,
   *    sphereSegments: 32, // decrease to improve performance
   *    cylinderSegments: 16, // decrease to improve performance
   *    staticScene: true, // disable if animation required
   *    defaultZoom: 1, // 1 will zoom to fit object exactly, <1 will add padding between object and box bounds
   *    zoomToFit2D: false // if true, will zoom to fit object only along the X and Y axes (not Z)
   *    extractAxis: false // will remove the axis from the main scene
   * }
   * There are several additional options used for debugging and testing,
   * please consult the source code directly for these.
   */
  settings?: any;

  /**
   * Hide/show nodes in scene by its name (key), value is 1 to show the node
   * and 0 to hide it.
   */
  toggleVisibility?: any;
  /**
   * File type to be downloaded as an image. Either png or dae
   */
  /**
   * Set to trigger a screenshot or scene download.
   * Must be an object with the following structure:
   * {
   *    "filetype": "png" // the image format ("png", "dae")
   * }
   * Passing this prop as an object ensures that
   * new requests are triggered any time the prop
   * is set.
   */
  imageRequest?: any;
  /**
   * THIS PROP IS SET AUTOMATICALLY
   * Data string for the image generated by imageRequest
   * This string can be downloaded as the filetype specified in your imageRequest object
   */
  imageType?: ExportType;
  /**
   * THIS PROP IS SET AUTOMATICALLY
   * Data string for the image generated on image button click
   */
  imageData?: string;
  /**
   * THIS PROP IS SET AUTOMATICALLY
   * Date string that represents the time imageData was set.
   * Use this prop in dash callbacks to trigger downloads of imageData.
   */
  imageDataTimestamp?: any;
  /**
   * List of options to show in file download dropdown
   */
  fileOptions?: string[];
  /**
   * THIS PROP IS SET AUTOMATICALLY
   * The last file type clicked in the file download menu
   */
  fileType?: string;
  /**
   * THIS PROP IS SET AUTOMATICALLY
   * Date string that represents the time fileType was set.
   * Use this prop in dash callbacks to trigger file downloads.
   */
  fileTimestamp?: any;
  onObjectClicked?: (value: any) => any;
  /**
   * Size of axis inlet
   */
  inletSize?: number;
  /**
   * Size of scene
   */
  sceneSize?: number | string;
  /**
   * Padding of axis inlet
   */
  inletPadding?: number;
  /**
   * Orientation of axis view
   */
  axisView?: string;
  /**
   * Animation
   *
   * Set up animation styles
   *
   * 'play'
   * 'none'
   * 'slider'
   */
  animation?: string;
  /**
   * THIS PROP IS SET AUTOMATICALLY
   * Object that maintains the current state of the camera.
   * e.g.
   * {
   *   position: {x: 0, y: 0, z: 0},
   *   quarternion: {x: 0, y: 0, z: 0, w: 0},
   *   zoom: 1,
   *   setByComponentId: "1",
   *   following: true
   * }
   */
  currentCameraState?: CameraState;
  /**
   * Object for setting the scene to a custom camera state.
   * When modified, the camera will update to new custom state.
   * e.g.
   * {
   *   position: {x: 0, y: 0, z: 0},
   *   quarternion: {x: 0, y: 0, z: 0, w: 0}, (optional)
   *   zoom: 1 (optional)
   * }
   */
  customCameraState?: CameraState;
  /**
   * Determines if control bar is visible
   * @default true
   */
  showControls?: boolean;
  /**
   * Determines if expand button in control bar is visible
   * @default true
   */
  showExpandButton?: boolean;
  /**
   * Determines if image download button in control bar is visible
   * @default true
   */
  showImageButton?: boolean;
  /**
   * Determines if file export button in control bar is visible
   * @default true
   */
  showExportButton?: boolean;
  /**
   * Determines if return to original position button in control bar is visible
   * @default true
   */
  showPositionButton?: boolean;
  /**
   * Override toolbar tooltip and export menu text.
   */
  texts?: Partial<CrystalToolkitSceneTexts>;
}

/**
 * This component is intended to draw simple 3D scenes using the popular
 * Three.js scene graph library. In particular, the JSON representing the 3D scene
 * is intended to be human-readable, and easily generated via Python. This is not
 * intended to be a replacement for a full scene graph library, but for rapid
 * prototyping by non-experts.
 */
export const CrystalToolkitAnimationScene: React.FC<CrystalToolkitAnimationSceneProps> = ({
  imageType = ExportType.png,
  imageRequest = {},
  setProps = () => null,
  showControls = true,
  showExpandButton = true,
  showImageButton = true,
  showExportButton = true,
  texts: textsProp,
  ...otherProps
}) => {
  const texts = mergeTexts(DEFAULT_CRYSTAL_TOOLKIT_SCENE_TEXTS, textsProp);

  const props = {
    imageType,
    imageRequest,
    setProps,
    showControls,
    showExpandButton,
    showImageButton,
    showExportButton,
    texts,
    ...otherProps
  };
  /**
   * mount nodes, those are passed in the template and are populated when
   * the component is mounted
   */
  const mountNodeRef = useRef(null);

  /**
   * Wrap mountNodeRef in a resize observer so that the scene
   * can resize properly even when the window size doesn't change
   */
  useResizeObserver<HTMLDivElement>({
    ref: mountNodeRef,
    onResize: () => {
      if (scene.current) {
        scene.current.resizeRendererToDisplaySize();
      }
    }
  });

  const mountNodeDebugRef = useRef(null);
  // we use a ref to keep a reference to the underlying scene
  const scene = useRef<Scene | null>(null);
  const sceneSubscriptionRef = useRef<{ unsubscribe: () => void } | null>(null);
  const [expanded, setExpanded] = useState(false);
  const [showSettingsPanel, setShowSettingsPanel] = useState(false);
  const { settingsPanel, bottomPanel, hasSettingsPanel, hasBottomPanel } = useScenePanels(
    props.children
  );
  const { panelRef: settingsPanelRef, triggerRef: settingsTriggerRef } = useDismissiblePanel(
    showSettingsPanel,
    () => setShowSettingsPanel(false)
  );
  const { cameraDispatch, componentIdRef, resetCamera } = useSceneCameraSync({
    scene,
    setProps: props.setProps,
    customCameraState: props.customCameraState
  });
  const tooltipId = useId().replace(/[:]/g, '-');

  // called after the component is mounted, so refs are correctly populated
  useEffect(() => {
    const mountNode = mountNodeRef.current;
    if (!mountNode) {
      return;
    }
    const { scene: sceneInstance, subscription } = createSceneLifecycle({
      data: props.data,
      mountNode,
      settings: props.settings,
      inletSize: props.inletSize,
      inletPadding: props.inletPadding,
      mountNodeDebug: mountNodeDebugRef.current ?? undefined,
      onObjectClicked: props.onObjectClicked,
      onCameraChange: (position, quaternion, zoom) => {
        cameraDispatch?.({
          type: CameraReducerAction.NEW_POSITION,
          payload: {
            componentId: componentIdRef.current,
            position,
            quaternion,
            zoom
          }
        });
      },
      setProps: props.setProps,
      removeListeners: true,
      animateOnMount: true
    });
    scene.current = sceneInstance;
    sceneSubscriptionRef.current = subscription;
    return () => {
      sceneSubscriptionRef.current?.unsubscribe();
      sceneSubscriptionRef.current = null;
      sceneInstance.onDestroy();
      scene.current = null;
    };
  }, []);

  useSceneSharedEffects({
    scene,
    mountNodeDebugRef,
    debug: props.debug,
    data: props.data,
    toggleVisibility: props.toggleVisibility,
    inletSize: props.inletSize,
    inletPadding: props.inletPadding,
    axisView: props.axisView,
    sceneSize: props.sceneSize,
    imageRequest: props.imageRequest,
    setProps: props.setProps,
    animation: props.animation,
    bypassRenderingOnData: false
  });

  useEffect(() => {
    if (!scene.current) {
      return;
    }

    const syncSceneSize = () => {
      const mountNode = mountNodeRef.current;
      if (!scene.current || !mountNode) {
        return;
      }
      scene.current.attachToMountNode?.(mountNode);
      scene.current.resizeRendererToDisplaySize();
      scene.current.renderScene();
    };

    syncSceneSize();
    const frameId = requestAnimationFrame(syncSceneSize);
    return () => cancelAnimationFrame(frameId);
  }, [expanded]);

  /**
   * Make atom move
   */

  const size = getSceneSize(props.sceneSize);

  // NOTE(chab) we could let the user opt for a flex layout, instead of using relative/absolute
  return (
    <Enlargeable
      id={props.id}
      className={clsx('mcv-root', props.className)}
      hideButton
      expanded={expanded}
      setExpanded={setExpanded}
    >
      <div className="ms-scene" data-slot="viewer-shell">
        {props.showControls && (
          <>
            <SceneToolbar
              expanded={expanded}
              onToggleExpanded={() => setExpanded(!expanded)}
              hasSettingsPanel={hasSettingsPanel}
              showSettingsPanel={showSettingsPanel}
              onToggleSettingsPanel={() => setShowSettingsPanel(!showSettingsPanel)}
              settingsTriggerRef={settingsTriggerRef}
              onResetCamera={resetCamera}
              sceneRef={scene}
              setProps={props.setProps}
              tooltipId={tooltipId}
              texts={texts}
              fileOptions={props.fileOptions}
              showExpandButton={props.showExpandButton}
              showImageButton={props.showImageButton}
              showExportButton={props.showExportButton}
              showPositionButton={props.showPositionButton}
            />
          </>
        )}
        {hasSettingsPanel && (
          <div
            className={clsx('ms-scene-settings-panel', {
              'ms-is-hidden': !showSettingsPanel
            })}
            data-slot="settings-panel"
            ref={settingsPanelRef}
          >
            <ModalCloseButton className="ms-delete" onClick={() => setShowSettingsPanel(false)} />
            {settingsPanel}
          </div>
        )}
        {hasBottomPanel && <div className="ms-scene-bottom-panel" data-slot="legend-panel">{bottomPanel}</div>}
        <div className="ms-scene-square-wrapper" data-slot="scene-frame">
          <div className="ms-scene-square" style={{ width: size, height: size }}>
            <div
              id={props.id!}
              style={{ ...MOUNT_NODE_STYLE, width: size, height: size }}
              className={MOUNT_NODE_CLASS}
              ref={mountNodeRef}
            />
          </div>
          {props.debug && (
            <div style={DEBUG_STYLE} className={MOUNT_DEBUG_NODE_CLASS} ref={mountNodeDebugRef} />
          )}

          {props.animation === AnimationStyle.SLIDER && (
            <RangeSlider
              domain={[0, 100]}
              onChange={(values) => scene.current!.updateTime(values[0] / 100)}
            />
          )}
        </div>
      </div>
    </Enlargeable>
  );
};
